config/routes.rb
Rails.application.routes.draw do
  resources :curricula, only: [:show, :index]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#top'
  resources :articles, only: [:show, :index] do
    collection do
      post 'purchase'
    end
    resources :reads, only: [:create, :destroy]
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :curriculum
  has_many :reads, dependent: :destroy
end

app/models/curriculum.rb
class Curriculum < ApplicationRecord
  has_many :articles
  include CurriculumImageUploader[:image]
end

app/models/read.rb
class Read < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reads, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @reads = @article.reads
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def purchase
    number = params[:number]
    cvc = params[:cvc]
    exp_month = params[:exp_month]
    exp_year = params[:exp_year]
    Payjp.api_key = PAYJP_SECRET_KEY
    # token = create_token(number, cvc, exp_month, exp_year)
    # Payjp::Customer.create(card: params['payjp-token'])
    # Payjp::Customer.retrieve('cus_cdf736b4e0dbc486f204cb91fdaf')
    Payjp::Subscription.create(
    customer: 'cus_cdf736b4e0dbc486f204cb91fdaf',
    plan:     'toBeginner',
  )
    # Payjp::Charge.create(currency: 'jpy', amount: 1000, card: params['payjp-token'])
    redirect_to root_path, notice: "支払いが完了しました"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
      puts "ここここここ"
    end

    def create_token(number, cvc, exp_month, exp_year)
    token = Payjp::Token.create(
      card: {
        number:    number,
        cvc:       cvc,
        exp_year:  exp_year,
        exp_month: exp_month,
      }
    )
    return token.id
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :url, :curriculum_id, :user_id)
    end
end

app/controllers/curricula_controller.rb
class CurriculaController < InheritedResources::Base

  before_action :set_article, only: [:show]

  # GET /articles
  # GET /articles.json
  def index
    @curriculums = Curriculum.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @articles = @curriculum.articles.order(id: "DESC")
  end

  private
    def curriculum_params
      params.require(:curriculum).permit(:title)
    end
      # Use callbacks to share common setup or constraints between actions.
    def set_article
      @curriculum = Curriculum.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def curriculum
  end
end

app/controllers/reads_controller.rb
class ReadsController < ApplicationController
  def create
    @read = Read.create(user_id: current_user.id, article_id: params[:article_id])
    @read = Read.where(article_id: params[:article_id])
    @article = Article.find(params[:article_id])
  end

  def destroy
    read = Read.find_by(user_id: current_user.id, article_id: params[:article_id])
    read.destroy
    @reads = Read.where(article_id: params[:article_id])
    @article = Article.find(params[:article_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reads_helper.rb
module ReadsHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>
<%= form_tag(action: :purchase, method: :post) do %>
   <script type="text/javascript" src="https://checkout.pay.jp" class="payjp-button" data-key=<%= PAYJP_PUBLIC_KEY%>>
     
   </script>
<% end %>
<%= link_to 'Back', articles_path %>

app/views/articles/product.html.erb
<%= form_tag(action: :purchase, method: :post) do
          %script.payjp-button{"data-key" => "#{PAYJP_PUBLIC_KEY}", :src => "https://checkout.pay.jp", :type => "text/javascript"} %>

app/views/articles/show.html.erb
<section class="article-show-view">
  <div class="article-show-content">
    <%= image_tag @article.curriculum.image_url %>
    <p><%= @article.title %></p>
  <!-- <p><%= link_to "いいね", article_reads_path(@article.id), method: :post%></p> -->
  <!-- <div id="like-buttons"><%= render partial: 'reads/read', locals: { article: @article, reads: @reads} %></div> -->
  <div class="video">
    <iframe src="<%= @article.url %>" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
  </div>
  </div>
</section>

app/views/curricula/_form.html.erb
<%= form_with(model: curriculum, local: true) do |form| %>
  <% if curriculum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curriculum.errors.count, "error") %> prohibited this curriculum from being saved:</h2>

      <ul>
      <% curriculum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :curriculum_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/curricula/edit.html.erb
<h1>Editing Curriculum</h1>

<%= render 'form', curriculum: @curriculum %>

<%= link_to 'Show', @curriculum %> |
<%= link_to 'Back', curriculums_path %>

app/views/curricula/index.html.erb
<section class="curriculum-index">
  <div class="curriculum-content">
    <h1>カリキュラム一覧</h1>
    <% @curriculums.each do |curriculum| %>
    <%= link_to curricula_path(curriculum.id) do %>
      <div class="curriculum-card">
        <%= image_tag curriculum.image_url %>
        <p class="curriculum-card-title"><%= curriculum.title %></p>
        <p class="curriculum-card-description"><%= curriculum.description %></p>
      </div>
    <% end %>
    <% end %>
  </div>
</section>

app/views/curricula/new.html.erb
<h1>New Curriculum</h1>

<%= render 'form', curriculum: @curriculum %>

<%= link_to 'Back', curriculums_path %>

app/views/curricula/show.html.erb
<section class="curriculums-title-view clearfix">
  <%= image_tag @curriculum.image_url, class:"curriculums-title-image" %>
  <h2 class="curriculums-title"><%= @curriculum.title %></h2>
  <p class="curriculums-description"><%= @curriculum.description %></p>
</section>

<section class="curriculums-table">
  <ul>
    <% @articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
    <% end %>
  </ul>
</section>

app/views/home/curriculum.html.erb
<p>カリキュラムのページ</p>

app/views/home/top.html.erb
<section class="main">
  <div class="main-cover">
    <p class="main-title">初心者になる</p>
  </div>
</section>
<section class="about">
  <p class="abel about-title">CODE A to B</p>
  <p class="about-description">プログラミング素人を<span>初心者</span>にするサービスです。</p>
</section>

<section class="recommend clearfix">
  <div class="recommend-left">
    <div class="recommend-image">
      <div class="recommend-image-cover"></div>
    </div>
  </div>
  <div class="recommend-right">
    <p class="recommend-title">このような方にオススメ</p>
    <ul>
      <li>参考書を購入して学習して見たものの１ページ目から訳が分からず挫折してしまった</li>
      <li>これからプログラミングスクールに通いたいが、無知のままでは不安</li>
      <li>プログラミングを始めたいが何をしたら良いのかわからない</li>
    </ul>
  </div>
</section>

<section class="chara">
  <p class="chara-title">特徴</p>
  <p class="chara-description"><span class="chara-description-title abel">CODE A to B </span>は今までにない、プログラミング素人の <span class="chara-description-orange">1歩目</span> を支えるためのサービスです。<br><br><br>
  巷の参考書でプログラミング素人に向けて書かれたものは非常に少なく、難易度の高いものが多いので1歩も進めず挫折してしまう方がとても多いようです。<br>
  CODE A to B はプログラミングスキルを身に付けたい方の学習の <span>1歩目</span> として最適なカリキュラムを組んでいます。<br><br><br>
  しかし、注意していただきたいことがあります、<br>
  本サービスを受講してもプロレベルになることはできないというところです。<br><br>
  プログラミング学習において大切なことは1歩進むことです。<br>
  その1歩目を越えれば、勉強の仕方も自然とわかってきます。<br><br>
  スムーズな学習の1歩目を一緒に歩みましょう。
  </p>
</section>

<section class="curriculum">
  <h3 class="curriculum-title">学べること</h3>
  <div class="curriculum-ios-area clearfix">
    <%= image_tag "/image/f_f_business_31_s512_f_business_31_0bg.png", class:"curriculum-ios-image" %>
    <div class="curriculum-ios-text">
      <h4 class="curriculum-ios-title">iOSアプリ開発</h4>
      <p class="curriculum-ios-description">iOSアプリとは、iPhone専用のアプリです。iOSアプリ開発を通して、プログラミングの基本的な流れを学ぶことができます</p>
    </div>
  </div>
  <div class="curriculum-swift-area clearfix">
    <%= image_tag "/image/swiftlogo.png", class:"curriculum-swift-image" %>
    <div class="curriculum-swift-text">
      <h4 class="curriculum-swift-title">Swift</h4>
      <p class="curriculum-swift-description">iOSアプリ開発を中心に利用される人気のプログラミング言語。このSwiftの基本的な使用方法を学習することができます。</p>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AtoB</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Abel|Roboto+Mono" rel="stylesheet">
    <link href="https://fonts.googleapis.com/earlyaccess/sawarabigothic.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/earlyaccess/sawarabimincho.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="logo"><%= link_to "CODE A to B", root_path %></div>
      <div id="nav-drawer" class="clearfix">
        <input id="nav-input" type="checkbox" class="nav-unshown">
        <label id="nav-open" for="nav-input"><span></span></label>
        <label class="nav-unshown" id="nav-close" for="nav-input"></label>
        <div id="nav-content">
          <nav>
            <ul>
              <% if user_signed_in? %>
                <li><%= link_to "ログアウト",destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "ログイン", new_user_session_path %></li>
                <li><%= link_to "新規登録", new_user_registration_path %></li>
              <% end %>
              <li><%= link_to "カリキュラム", curricula_index_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/reads/_read.html.erb
<% if user_signed_in? %>
  <% if article.reads.find_by(user_id: current_user.id) %>

    <%= button_to article_read_path(article.id, article.reads.find_by(user_id: current_user.id).id), method: :delete, remote: true do %>

      <p>いいね解除</p>
      <span>
        <%= article.reads.count %>
      </span>
    <% end %>
  <% else %>
    <%= button_to article_reads_path(article.id),remote: true do %>
      <p>いいね</p>
      <span>
        <%= article.reads.count %>
      </span>
    <% end %>
  <% end %>
<% else %>
<p>いいね</p>
    <span>
      <%= article.reads.count %>
    </span>
<% end %>

app/views/reads/create.js.erb
$("#like-buttons").html("<%= j(render partial: 'read', locals: { article: @article, reads: @reads}) %>")

app/views/reads/destroy.js.erb
$("#like-buttons").html("<%= j(render partial: 'read', locals: { article: @article, reads: @reads}) %>")

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れた方はこちら！", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>